export type FormbarErrorCode =
  | "FORMBAR_PATH_EMPTY"
  | "FORMBAR_PATH_INVALID_DOT"
  | "FORMBAR_PATH_INVALID_POINTER"
  | "FORMBAR_PATH_INVALID_POINTER_ESCAPE"
  | "FORMBAR_PATH_MIXED_NAMESPACE"
  | "FORMBAR_PATH_NOT_DOT_SAFE"
  | "FORMBAR_EXTENSION_INCOMPATIBLE"
  | "FORMBAR_EXTENSION_INVALID_MANIFEST"
  | "FORMBAR_EXTENSION_DUPLICATE"
  | "FORMBAR_TIMEOUT"
  | "FORMBAR_RENDERER_UNKNOWN_TYPE"
  | "FORMBAR_PROTOTYPE_POLLUTION"
  | "FORMBAR_SUBMIT_CONCURRENT"
  | "FORMBAR_SUBMIT_NO_HANDLER"
  | "FORMBAR_ASYNC_IN_SYNC_PIPELINE"
  | "FORMBAR_RULE_WRITE_CONFLICT"
  | "FORMBAR_RULE_NON_CONVERGENT"
  | "FORMBAR_RULE_DISALLOWED_TARGET"
  | "FORMBAR_ASYNC_SCHEMA_IN_SYNC"
  | "FORMBAR_INVALID_VALIDATOR";

export class FormbarError extends Error {
  readonly code: FormbarErrorCode;

  constructor(code: FormbarErrorCode, message: string) {
    super(message);
    this.name = "FormbarError";
    this.code = code;
  }
}
