import { describe } from "vitest";
import { registerActionContextSpecs } from "./context-state.spec-action-context.js";
import { registerBridgeRaceAndParitySpecs } from "./context-state.spec-bridge-race-parity.js";
import { registerBridgeUnavailableSpecs } from "./context-state.spec-bridge-unavailable.js";
import { registerCompositionParitySpecs } from "./context-state.spec-composition-parity.js";
import { registerContextStateCoreSelectionLanesSpecs } from "./context-state.spec-core-selection-lanes.js";
import { registerDndSessionBrokerSpecs } from "./context-state.spec-dnd-session-broker.js";
import { registerDndSessionProtocolSpecs } from "./context-state.spec-dnd-session-protocol.js";
import { registerDockOverlayRenderingSpecs } from "./context-state.spec-dock-overlay-rendering.js";
import { registerDockPopoutActionRenderingSpecs } from "./context-state.spec-dock-popout-action-rendering.js";
import { registerDockSplitterDragSpecs } from "./context-state.spec-dock-splitter-drag.js";
import { registerDockTabDragDropSpecs } from "./context-state.spec-dock-tab-drag-drop.js";
import { createSpecHarness } from "./context-state.spec-harness.js";
import { registerIncomingTransferTransactionSpecs } from "./context-state.spec-incoming-transfer-transaction.js";
import { registerIntentRuntimeCompositionSpecs } from "./context-state.spec-intent-runtime-composition.js";
import { registerKeyboardA11ySpecs } from "./context-state.spec-keyboard-a11y.js";
import { registerContextStatePersistenceSpecs } from "./context-state.spec-persistence.js";
import { registerPlacementStrategySpecs } from "./context-state.spec-placement-strategy.js";
import { registerShellKeyboardActionSpecs } from "./context-state.spec-shell-keyboard-actions.js";
import { registerSyncPopoutDegradedSpecs } from "./context-state.spec-sync-popout-degraded.js";
import { registerTabDragDropSpecs } from "./context-state.spec-tab-drag-drop.js";

describe("context-state", () => {
	const harness = createSpecHarness();

	registerContextStateCoreSelectionLanesSpecs(harness);
	registerIntentRuntimeCompositionSpecs(harness);
	registerContextStatePersistenceSpecs(harness);
	registerKeyboardA11ySpecs(harness);
	registerSyncPopoutDegradedSpecs(harness);
	registerBridgeUnavailableSpecs(harness);
	registerTabDragDropSpecs(harness);
	registerDockTabDragDropSpecs(harness);
	registerActionContextSpecs(harness);
	registerCompositionParitySpecs(harness);
	registerBridgeRaceAndParitySpecs(harness);
	registerDndSessionProtocolSpecs(harness);
	registerIncomingTransferTransactionSpecs(harness);
	registerDndSessionBrokerSpecs(harness);
	registerDockPopoutActionRenderingSpecs(harness);
	registerDockSplitterDragSpecs(harness);
	registerDockOverlayRenderingSpecs(harness);
	registerShellKeyboardActionSpecs(harness);
	registerPlacementStrategySpecs(harness);
});
